apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: demo-chart
  name: { Values.pod.name }
spec:
  containers:
  - image: nginx
    name: { Values.service.name }
    ports:
      - containerPort: 80
        name: nginx-port
