apiVersion: v1
kind: Service
metadata:
  name: { Values.service.name }
spec:
  ports:
  - nodePort: { Values.service.nodePort }
    port: { Values.service.port }
    protocol: TCP
    targetPort: nginx-port
  selector:
    app.kubernetes.io/name: demo-chart
  type: NodePort
