#pod-svc.yml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: service-demo #user defined
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
      - containerPort: 80
        name: http-web-svc
