apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: service-demo
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
