apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mars-deployment1
  name: mars-deployment1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mars-deployment1
  template:
    metadata:
      labels:
        app: mars-deployment1
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: port
spec:
  type: NodePort
  selector:
    app: mars-deployment1
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
