apiVersion: v1
kind: Pod
metadata:
  name: mars-pod
spec:
  volumes:
    - name: mars-storage
      persistentVolumeClaim:
        claimName: mars-pvc
  containers:
    - name: mars-pod-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/mydata"
          name: mars-storage
