apiVersion: v1
kind: PersistentVolume
metadata:
  name: mars-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/mike/data"
