apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mars-deployment2
  name: mars-deployment2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mars-deployment2
  template:
    metadata:
      labels:
        app: mars-deployment2
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: port
spec:
  type: LoadBalancer
  selector:
    app: mars-deployment2
  ports:
    - port: 80
      targetPort: 80
